name: Setup Firebolt database and engine
description: >-
 Setup Firebolt database with the generated name. Then, setup an engine with the same
 name, which is attached to the created database
inputs:
  firebolt-client-id:
    description: Firebolt account username
    required: true
  firebolt-client-id:
    description: Firebolt account password
    required: true
  account:
    description: Account name
    required: true
  api-endpoint:
    description: Firebolt api address
    default: 'api.app.firebolt.io'
    required: false
  region:
    description: In which region to create the database
    default: 'us-east-1'
    required: false
    deprecationMessage: 'region parameter is not used anymore and will be removed in new versions'
  instance-type:
    description: Instance type of the running instance
    default: ''
    required: false
  db_suffix:
    description: Suffix to add to db name
    default: ''
    required: false
  engine-scale:
    description: Engine scale
    default: '1'
    required: false
    
outputs:
  database_name:
    description: Name of created database
  engine_name:
    description: Name of created engine
  engine_url:
    description: Endpoint of created engine
  stopped_engine_name:
    description: Name of created engine in stopped state
  stopped_engine_url:
    description: Endpoint of created engine in stopped state
        
runs:
  using: node16
  main: dist/setup/index.js
  post: dist/cleanup/index.js
